# Generated by Django 3.1.7 on 2021-03-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210317_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
