# Generated by Django 3.1.7 on 2021-03-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210317_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='alumno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='profesor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='perfil',
            name='visitante',
            field=models.BooleanField(default=True),
        ),
    ]
