# Generated by Django 3.1.7 on 2021-03-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='description',
            new_name='descripcion',
        ),
    ]
