# Generated by Django 3.1.7 on 2021-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210315_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.CharField(default='profesor', max_length=30),
            preserve_default=False,
        ),
    ]
