# Generated by Django 3.1.7 on 2021-03-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_curso_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='calificacion',
        ),
    ]
