# Generated by Django 3.1.7 on 2021-03-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210316_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
