# Generated by Django 3.1.7 on 2021-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210316_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
