# Generated by Django 3.1.7 on 2021-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_curso_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
