# Generated by Django 3.1.7 on 2021-03-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210325_1916'),
        ('visitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recomendacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.TextField()),
                ('nivel', models.CharField(default='m', max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
    ]
